apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
    spec:
      containers:
        - name: order-processor
          image: anhduc8702/halo-microservices-app-order-processor:35
          env:
            - name: KAFKA_BROKER
              value: "192.168.49.1:9092"
            # - name: DB_PATH
            #  value: "/data/orders.db"
          envFrom:
            - secretRef:
                name: mysql-credentials
          volumeMounts:
            - name: db-storage
              mountPath: /data
      volumes:
        - name: db-storage
          emptyDir: {}
